import {
  collection,
  doc,
  onSnapshot,
  orderBy,
  query,
} from "firebase/firestore";
import Head from "next/head";
import { useEffect, useState } from "react";
import { db } from "../utils/firebase";
import Thought from "../components/thoughts";
import Link from "next/link";
import {auth} from "/utils/firebase";
import { useRouter } from "next/router";

export default function Home() {
  const [allPosts, setAllposts] = useState();
  const route = useRouter();
  
  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllposts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
      return unsubscribe;
    });
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <>
      <Head>
        <title>Creative thoughts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main-page-content">
        <h2>{auth.currentUser? "This might interest you" : "Join Today to see posts from other users"}</h2>
        {allPosts?.map((posts) => (
          <Thought key={posts.id} {...posts}>
            <Link href={{pathname : `/${posts.id}`,query : posts}}>
              <button className="comments">{posts.comments?.length}  comments</button>
            </Link>
          </Thought>
        ))}
      </div>
    </>
  );
}
